import esbuild from "esbuild";
import process from "node:process";

// Bundles both entry points as classic (non-module) content-script-
// and popup-safe IIFEs, output flat at the package root alongside
// manifest.json/popup.html/icons — so `browser-flowgo/` itself, as
// checked out, is a directly loadable unpacked extension (Chrome:
// chrome://extensions → Load unpacked; Firefox: about:debugging →
// Load Temporary Add-on → manifest.json) once `pnpm build` has run.
const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD.
Source: https://github.com/lassediercks/flowgo/tree/main/browser-flowgo
*/
`;

const production = process.argv[2] === "production";

const common = {
  bundle: true,
  format: "iife",
  target: "es2020",
  logLevel: "info",
  sourcemap: production ? false : "inline",
  minify: production,
  banner: { js: banner },
};

async function run() {
  const contentCtx = await esbuild.context({ ...common, entryPoints: ["src/content.ts"], outfile: "content.js" });
  const popupCtx = await esbuild.context({ ...common, entryPoints: ["src/popup.ts"], outfile: "popup.js" });

  if (production) {
    await Promise.all([contentCtx.rebuild(), popupCtx.rebuild()]);
    await Promise.all([contentCtx.dispose(), popupCtx.dispose()]);
  } else {
    await Promise.all([contentCtx.watch(), popupCtx.watch()]);
  }
}

run();
