import esbuild from "esbuild";
import process from "node:process";

// Standard obsidian-sample-plugin esbuild pattern: bundle main.ts (which
// pulls in ../src/render/inline.ts directly, see src/render.ts) into a
// single main.js, with `obsidian`/`electron` left external since the
// Obsidian app provides those at runtime.
const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD.
Source: https://github.com/lassediercks/flowgo/tree/main/obsidian-flowgo
*/
`;

const production = process.argv[2] === "production";

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["main.ts"],
  bundle: true,
  external: ["obsidian", "electron"],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: production ? false : "inline",
  outfile: "main.js",
  minify: production,
});

if (production) {
  await context.rebuild();
  await context.dispose();
  process.exit(0);
} else {
  await context.watch();
}
