#!/usr/bin/env node
// Regenerates media/flowgo-inline.js, the vendored copy of the
// dependency-free renderer bundle produced by `pnpm build:inline` at the
// repo root (see ../vite.inline.config.ts, which bundles
// ../src/render/inline.ts into a global `FlowgoInline.renderFlowgo(...)`).
//
// `dist-inline/` at the repo root is gitignored and @flowgo/editor is not
// published to npm, so this extension can't `import` or `require` the
// renderer like a normal dependency — it vendors a built copy instead,
// regenerated by this script (run via `npm run build`, see package.json).
//
// Run from anywhere; paths below are resolved relative to this file.
import { execFileSync } from "node:child_process";
import { copyFileSync, existsSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..", "..");
const builtBundle = resolve(repoRoot, "dist-inline", "flowgo-inline.js");
const mediaDir = resolve(here, "..", "media");
const vendoredBundle = resolve(mediaDir, "flowgo-inline.js");

console.log("[vendor-inline] pnpm build:inline (in %s)", repoRoot);
execFileSync("pnpm", ["build:inline"], { cwd: repoRoot, stdio: "inherit" });

if (!existsSync(builtBundle)) {
  console.error("[vendor-inline] expected build output missing: %s", builtBundle);
  process.exit(1);
}

mkdirSync(mediaDir, { recursive: true });
copyFileSync(builtBundle, vendoredBundle);
console.log("[vendor-inline] copied %s -> %s", builtBundle, vendoredBundle);
